export const defaultLayout = 'normal'

export const naiveThemeOverrides = {
  common: {
    primaryColor: '#316C72FF',
    primaryColorHover: '#316C72E3',
    primaryColorPressed: '#2B4C59FF',
    primaryColorSuppl: '#316C72E3',

    infoColor: '#2080F0FF',
    infoColorHover: '#4098FCFF',
    infoColorPressed: '#1060C9FF',
    infoColorSuppl: '#4098FCFF',

    successColor: '#18A058FF',
    successColorHover: '#36AD6AFF',
    successColorPressed: '#0C7A43FF',
    successColorSuppl: '#36AD6AFF',

    warningColor: '#F0A020FF',
    warningColorHover: '#FCB040FF',
    warningColorPressed: '#C97C10FF',
    warningColorSuppl: '#FCB040FF',

    errorColor: '#D03050FF',
    errorColorHover: '#DE576DFF',
    errorColorPressed: '#AB1F3FFF',
    errorColorSuppl: '#DE576DFF',
  },
}

export const basePermissions = [
  {
    id: 2,
    name: '系统管理',
    code: 'SysMgt',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:settings',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    children: [
      {
        id: 1,
        name: '菜单管理',
        code: 'Resource_Mgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/resource',
        redirect: null,
        icon: 'i-fe:list',
        component: '/src/views/pms/resource/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 3,
        name: '角色管理',
        code: 'RoleMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/role',
        redirect: null,
        icon: 'i-fe:user-check',
        component: '/src/views/pms/role/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
        children: [
          {
            id: 5,
            name: '分配用户',
            code: 'RoleUser',
            type: 'MENU',
            parentId: 3,
            path: '/pms/role/user/:roleId',
            redirect: null,
            icon: 'i-fe:user-plus',
            component: '/src/views/pms/role/role-user.vue',
            layout: 'full',
            keepAlive: null,
            method: null,
            description: null,
            show: false,
            enable: true,
            order: 1,
          },
        ],
      },
      {
        id: 4,
        name: '用户管理',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        icon: 'i-fe:user',
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 3,
        children: [
          {
            id: 13,
            name: '创建新用户',
            code: 'AddUser',
            type: 'BUTTON',
            parentId: 4,
            path: null,
            redirect: null,
            icon: null,
            component: null,
            layout: null,
            keepAlive: null,
            method: null,
            description: null,
            show: true,
            enable: true,
            order: 1,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: '业务管理',
    code: 'BusinessManage',
    type: 'MENU',
    parentId: null,
    path: null,
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    children: [
      // {
      //   id: 7,
      //   name: '图片上传',
      //   code: 'ImgUpload',
      //   type: 'MENU',
      //   parentId: 6,
      //   path: '/demo/upload',
      //   redirect: null,
      //   icon: 'i-fe:image',
      //   component: '/src/views/demo/upload/index.vue',
      //   layout: 'simple',
      //   keepAlive: true,
      //   method: null,
      //   description: null,
      //   show: true,
      //   enable: true,
      //   order: 2,
      // },
      {
        id: 7,
        name: '合作伙伴图标管理',
        code: 'PartnerIconManage',
        type: 'MENU',
        parentId: 6,
        path: '/business/partner-icon-manage',
        redirect: null,
        icon: 'i-fe:image',
        component: '/src/views/business/PartnerIconManage.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 3,
      },
    ],
  },
  {
    id: 8,
    name: '个人资料',
    code: 'UserProfile',
    type: 'MENU',
    parentId: null,
    path: '/profile',
    redirect: null,
    icon: 'i-fe:user  ',
    component: '/src/views/profile/index.vue',
    layout: null,
    keepAlive: null,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 99,
  },
  /*
  {
    id: 9,
    name: '基础功能',
    code: 'Base',
    type: 'MENU',
    parentId: null,
    path: '',
    redirect: null,
    icon: 'i-fe:grid',
    component: null,
    layout: '',
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    children: [
      {
        id: 10,
        name: '基础组件',
        code: 'BaseComponents',
        type: 'MENU',
        parentId: 9,
        path: '/base/components',
        redirect: null,
        icon: 'i-me:awesome',
        component: '/src/views/base/index.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 11,
        name: 'Unocss',
        code: 'Unocss',
        type: 'MENU',
        parentId: 9,
        path: '/base/unocss',
        redirect: null,
        icon: 'i-me:awesome',
        component: '/src/views/base/unocss.vue',
        layout: null,
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 2,
      },
      {
        id: 12,
        name: 'KeepAlive',
        code: 'KeepAlive',
        type: 'MENU',
        parentId: 9,
        path: '/base/keep-alive',
        redirect: null,
        icon: 'i-me:awesome',
        component: '/src/views/base/keep-alive.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 3,
      },
      {
        id: 14,
        name: '图标 Icon',
        code: 'Icon',
        type: 'MENU',
        parentId: 9,
        path: '/base/icon',
        redirect: null,
        icon: 'i-fe:feather',
        component: '/src/views/base/unocss-icon.vue',
        layout: '',
        keepAlive: null,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 0,
      },
    ],
  },
  **/
]
